//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace accAfpslaiEmvSrvc
{
    using System;
    using System.Collections.Generic;
    
    public partial class card
    {
        public int id { get; set; }
        public Nullable<int> member_id { get; set; }
        public string cardNo { get; set; }
        public Nullable<System.DateTime> date_CMS { get; set; }
        public Nullable<System.DateTime> date_CBS { get; set; }
        public Nullable<System.DateTime> date_post { get; set; }
        public Nullable<System.TimeSpan> time_post { get; set; }
        public Nullable<bool> is_cancel { get; set; }
    }
}
