//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace accAfpslaiEmvSrvc
{
    using System;
    using System.Collections.Generic;
    
    public partial class cps_card_elements
    {
        public int id { get; set; }
        public string element { get; set; }
        public Nullable<int> x { get; set; }
        public Nullable<int> y { get; set; }
        public Nullable<int> width { get; set; }
        public Nullable<int> height { get; set; }
        public string font_name { get; set; }
        public Nullable<int> font_size { get; set; }
        public Nullable<int> font_style { get; set; }
        public string element_type { get; set; }
        public Nullable<System.DateTime> date_post { get; set; }
        public Nullable<System.TimeSpan> time_post { get; set; }
        public Nullable<System.DateTime> last_updated { get; set; }
    }
}
