//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace accAfpslaiEmvSrvc
{
    using System;
    using System.Collections.Generic;
    
    public partial class dcs_system_setting
    {
        public int id { get; set; }
        public Nullable<int> cif_length { get; set; }
        public Nullable<int> member_type_assoc_allow_yrs { get; set; }
        public Nullable<int> member_type_reg_allow_yrs { get; set; }
        public Nullable<int> cardname_length { get; set; }
        public string system_default_password { get; set; }
        public Nullable<System.DateTime> last_updated { get; set; }
    }
}
