//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace accAfpslaiEmvSrvc
{
    using System;
    using System.Collections.Generic;
    
    public partial class member
    {
        public int id { get; set; }
        public string cif { get; set; }
        public string last_name { get; set; }
        public string first_name { get; set; }
        public string middle_name { get; set; }
        public string suffix { get; set; }
        public string gender { get; set; }
        public Nullable<System.DateTime> date_birth { get; set; }
        public Nullable<int> civil_status_id { get; set; }
        public Nullable<int> membership_type_id { get; set; }
        public Nullable<int> membership_status_id { get; set; }
        public Nullable<System.DateTime> membership_date { get; set; }
        public string contact_nos { get; set; }
        public string mobile_nos { get; set; }
        public string emergency_contact_name { get; set; }
        public string emergency_contact_nos { get; set; }
        public Nullable<int> principal_associate_type_id { get; set; }
        public string principal_cif { get; set; }
        public string principal_name { get; set; }
        public string cca_no { get; set; }
        public Nullable<int> user_id { get; set; }
        public string terminal_id { get; set; }
        public Nullable<int> branch_id { get; set; }
        public string online_reference_number { get; set; }
        public string card_name { get; set; }
        public string email { get; set; }
        public Nullable<int> print_type_id { get; set; }
        public Nullable<int> recard_reason_id { get; set; }
        public Nullable<System.DateTime> date_post { get; set; }
        public Nullable<System.TimeSpan> time_post { get; set; }
        public Nullable<bool> is_cancel { get; set; }
    }
}
