//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace accAfpslaiEmvSrvc
{
    using System;
    using System.Collections.Generic;
    
    public partial class membership_status
    {
        public int id { get; set; }
        public string membershipStatus { get; set; }
        public Nullable<bool> is_deleted { get; set; }
        public string cbsCode { get; set; }
    }
}
