//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace accAfpslaiEmvSrvc
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class afpslai_emvEntities : DbContext
    {
        public afpslai_emvEntities()
            : base("name=afpslai_emvEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<address> addresses { get; set; }
        public virtual DbSet<api_request_log> api_request_log { get; set; }
        public virtual DbSet<associate_type> associate_type { get; set; }
        public virtual DbSet<branch> branches { get; set; }
        public virtual DbSet<card> cards { get; set; }
        public virtual DbSet<civil_status> civil_status { get; set; }
        public virtual DbSet<country> countries { get; set; }
        public virtual DbSet<cps_card_elements> cps_card_elements { get; set; }
        public virtual DbSet<dcs_system_setting> dcs_system_setting { get; set; }
        public virtual DbSet<member> members { get; set; }
        public virtual DbSet<membership_status> membership_status { get; set; }
        public virtual DbSet<membership_type> membership_type { get; set; }
        public virtual DbSet<online_registration> online_registration { get; set; }
        public virtual DbSet<print_type> print_type { get; set; }
        public virtual DbSet<recard_reason> recard_reason { get; set; }
        public virtual DbSet<system_log> system_log { get; set; }
        public virtual DbSet<system_role> system_role { get; set; }
        public virtual DbSet<system_user> system_user { get; set; }
        public virtual DbSet<userlogon> userlogons { get; set; }
    }
}
