//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace accAfpslaiEmvSrvc
{
    using System;
    using System.Collections.Generic;
    
    public partial class userlogon
    {
        public int id { get; set; }
        public string user_name { get; set; }
        public Nullable<System.DateTime> login_date { get; set; }
        public Nullable<System.TimeSpan> login_time { get; set; }
        public Nullable<System.DateTime> logout_date { get; set; }
        public Nullable<System.TimeSpan> logout_time { get; set; }
        public string system { get; set; }
    }
}
